-- ============================================
-- PROJECT: Store Sales Productivity Analysis
-- ============================================

-- Business Problem
-- The company runs 66 physical stores across multiple countries. Each store occupies a different 
-- amount of floor space (Square Meters), but we don't know if that space is being used efficiently. 
-- Some stores might be making great sales for their size, while others might be large but underperforming 
-- —> wasting rent, staff, and inventory space.

-- Clear Goal
-- Find out how much revenue each physical store generates per square meter, 
-- rank stores from best to worst on this measure, and identify which stores 
-- are underperforming relative to their size — so leadership can decide where 
-- to expand, shrink, or close store space.

USE sales_analytics_db;

-- ============================================
-- SECTION 1: BASE DATA CHECK
-- Q: How many physical stores exist, and do all 
-- have valid Square Meters values?
-- ============================================
SELECT 
	COUNT(*) AS [Total Stores],
	SUM(CASE WHEN Square_Meters IS NULL OR Square_Meters = 0 THEN 1 ELSE 0 END) AS [Invalid Square Meters Value]
FROM dbo.Stores
WHERE dbo.Stores.StoreKey <> 0;
-- ============================================
-- 66 physical stores in total, all with valid Square Meters.
-- Only StoreKey 0 (Online) is excluded.
-- ============================================

-- ================================================================
-- SECTION 2: STORE-LEVEL REVENUE
-- Q: What is the total revenue generated by each physical store, 
--    including stores with zero sales?
-- ================================================================
SELECT
	St.StoreKey,
	St.Country, 
	St.Square_Meters,
	St.Open_Date,
	COALESCE(SUM(S.Quantity * P.Unit_Price_USD), 0) AS [Total Revenue]
FROM Stores St
LEFT JOIN Sales S
	ON St.StoreKey = S.StoreKey
LEFT JOIN Products P
	ON S.ProductKey = P.ProductKey
WHERE St.StoreKey <> 0
GROUP BY St.StoreKey, St.Country, St.State, St.Square_Meters, St.Open_Date
ORDER BY [Total Revenue] DESC;
-- ================================================================
-- 9 out of 66 stores made zero revenue, despite having decent floor space.
-- These are the biggest red flags in the whole dataset.
-- ================================================================

-- ================================================================
-- SECTION 3: REVENUE PER SQUARE METER
-- Q: What is each store's revenue-per-sqm, and how do stores 
--    rank best to worst?
-- ================================================================
WITH StoreRevenue AS (
	SELECT
	St.StoreKey,
	St.Country, 
	St.Square_Meters,
	St.Open_Date,
	COALESCE(SUM(S.Quantity * P.Unit_Price_USD), 0) AS [Total Revenue]
FROM Stores St
LEFT JOIN Sales S
	ON St.StoreKey = S.StoreKey
LEFT JOIN Products P
	ON S.ProductKey = P.ProductKey
WHERE St.StoreKey <> 0
GROUP BY St.StoreKey, St.Country, St.State, St.Square_Meters, St.Open_Date
)
SELECT 
	StoreKey,
    Country,
    Square_Meters,
    [Total Revenue],
    ROUND([Total Revenue] / NULLIF(Square_Meters, 0), 2) AS RevenuePerSqm,
	RANK() OVER (ORDER BY [Total Revenue] / NULLIF(Square_Meters, 0) DESC) AS ProductivityRank
FROM StoreRevenue
ORDER BY RevenuePerSqm DESC;
-- ================================================================
-- Top-ranked stores earn high revenue per sqm — space is being used well.
-- The 9 zero-revenue stores rank last, tied at 0 — space is wasted, not just underused.
-- ================================================================

-- ================================================================
-- SECTION 4: COUNTRY-LEVEL ROLLUP
-- Q: Is underperformance concentrated in specific countries, or 
--    spread across all of them?
-- ================================================================
WITH StoreRevenue AS (
    SELECT 
        st.StoreKey,
        st.Country,
        st.Square_Meters,
        COALESCE(SUM(s.Quantity * p.Unit_Price_USD), 0) AS [Total Revenue]
    FROM Stores st
    LEFT JOIN Sales s 
        ON st.StoreKey = s.StoreKey
    LEFT JOIN Products p 
        ON s.ProductKey = p.ProductKey
    WHERE st.StoreKey <> 0
    GROUP BY st.StoreKey, st.Country, st.Square_Meters
)
SELECT 
    Country,
    COUNT(StoreKey) AS NumStores,
    SUM([Total Revenue]) AS CountryRevenue,
    SUM(Square_Meters) AS CountrySqm,
    ROUND(SUM([Total Revenue]) / NULLIF(SUM(Square_Meters), 0), 2) AS AvgRevenuePerSqm
FROM StoreRevenue
GROUP BY Country
ORDER BY AvgRevenuePerSqm DESC;
-- ================================================================
-- US looks best on paper (highest avg revenue/sqm), but it also has the 
-- most dead stores (4 of 9) — just hidden because it has 24 stores total.
-- Netherlands and Australia look worst, but that's because they have very 
-- few stores, so even 1 dead store drags their average way down.
-- Lesson: country averages can hide problems in big markets and 
-- exaggerate them in small ones.
-- ================================================================

-- ================================================================
-- SECTION 5: STORE SIZE SEGMENTATION
-- Q: Do small, medium, and large stores differ in average 
--    revenue-per-sqm?
-- ================================================================
WITH StoreRevenue AS (
    SELECT 
        st.StoreKey,
        st.Square_Meters,
        COALESCE(SUM(s.Quantity * p.Unit_Price_USD), 0) AS [Total Revenue]
    FROM Stores st
    LEFT JOIN Sales s 
        ON st.StoreKey = s.StoreKey
    LEFT JOIN Products p 
        ON s.ProductKey = p.ProductKey
    WHERE st.StoreKey <> 0
    GROUP BY st.StoreKey, st.Square_Meters
),
Sized AS (
    SELECT *,
        CASE 
            WHEN Square_Meters < 1000 THEN 'Small'
            WHEN Square_Meters BETWEEN 1000 AND 2000 THEN 'Medium'
            ELSE 'Large'
        END AS [Size Bucket]
    FROM StoreRevenue
)
SELECT 
    [Size Bucket],
    COUNT(StoreKey) AS [Total Stores],
    ROUND(AVG([Total Revenue] / NULLIF(Square_Meters, 0)), 2) AS AvgRevenuePerSqm
FROM Sized
GROUP BY [Size Bucket]
ORDER BY AvgRevenuePerSqm DESC;
-- ================================================================
-- Small stores (13) are the most productive: $575/sqm.
-- Medium stores (48): $485/sqm. Large stores (5): $410/sqm, the worst.
-- Bigger floor space is not paying off — small stores squeeze more 
-- revenue out of every sqm than large ones.
-- ================================================================

-- ================================================================
-- SECTION 6: STORE AGE CHECK
-- Q: Are underperforming stores mostly newer stores (still 
--    ramping up) or older stores (genuine problem)?
-- ================================================================
WITH StoreRevenue AS (
    SELECT 
        st.StoreKey,
        st.Open_Date,
        st.Square_Meters,
        COALESCE(SUM(s.Quantity * p.Unit_Price_USD), 0) AS TotalRevenue
    FROM Stores st
    LEFT JOIN Sales s 
        ON st.StoreKey = s.StoreKey
    LEFT JOIN Products p 
        ON s.ProductKey = p.ProductKey
    WHERE st.StoreKey <> 0
    GROUP BY st.StoreKey, st.Open_Date, st.Square_Meters
)
SELECT 
    YEAR(Open_Date) AS OpenYear,
    COUNT(StoreKey) AS NumStores,
    ROUND(AVG(TotalRevenue / NULLIF(Square_Meters, 0)), 2) AS AvgRevenuePerSqm
FROM StoreRevenue
GROUP BY YEAR(Open_Date)
ORDER BY OpenYear;
-- ================================================================
-- Not a simple "older = worse" story. 2007 and 2009 stores are the 
-- worst vintages ($223 and $317/sqm) — but other old stores (2005, 2010, 
-- 2012, 2013) are perfectly healthy (~$430-500/sqm).
-- So it's specific batches of stores, not age itself, causing the problem.
-- ================================================================

-- ================================================================
-- SECTION 7: OUTLIER FLAGGING
-- Q: Which stores deviate significantly from their country 
--    average revenue-per-sqm (best/worst outliers)?
-- ================================================================
WITH StoreRevenue AS (
    SELECT 
        st.StoreKey,
        st.Country,
        st.Square_Meters,
        COALESCE(SUM(s.Quantity * p.Unit_Price_USD), 0) AS [Total Revenue]
    FROM Stores st
    LEFT JOIN Sales s 
        ON st.StoreKey = s.StoreKey
    LEFT JOIN Products p 
        ON s.ProductKey = p.ProductKey
    WHERE st.StoreKey <> 0
    GROUP BY st.StoreKey, st.Country, st.Square_Meters
),
WithCountryAvg AS (
    SELECT *,
        [Total Revenue] / NULLIF(Square_Meters, 0) AS RevenuePerSqm,
        AVG([Total Revenue] / NULLIF(Square_Meters, 0)) OVER (PARTITION BY Country) AS CountryAvgRevPerSqm
    FROM StoreRevenue
)
SELECT 
    StoreKey,
    Country,
    Square_Meters,
    ROUND(RevenuePerSqm, 2) AS RevenuePerSqm,
    ROUND(CountryAvgRevPerSqm, 2) AS CountryAvgRevPerSqm,
    ROUND(RevenuePerSqm - CountryAvgRevPerSqm, 2) AS DeviationFromCountryAvg
FROM WithCountryAvg
ORDER BY DeviationFromCountryAvg ASC;
-- ================================================================
-- Best: Store 66 (US) beats its country average by $805/sqm — the 
-- single best-run store in the dataset.
-- Worst: The 4 dead US stores (52, 46, 58, 60) fall hardest since the 
-- US average is high ($648). Dead stores in Canada, Germany, Netherlands, 
-- Australia show smaller dollar gaps only because those countries already 
-- have lower averages — the failure is just as real, it's less visible here.
-- ================================================================

CREATE VIEW vw_Stores AS
SELECT StoreKey, Country, Square_Meters, Open_Date
FROM Stores WHERE StoreKey <> 0;

CREATE VIEW vw_Sales AS
SELECT StoreKey, ProductKey, Quantity
FROM Sales WHERE StoreKey <> 0;

CREATE VIEW vw_Products AS
SELECT ProductKey, Unit_Price_USD
FROM Products;